<?php

  function exceptionHandler($e) {
    $msg = array("status" => "500", "message" => $e->getMessage(), "file" => $e->getFile(), "line" => $e->getLine());
    
    $usr_msg = array("status" => "500", "message" => "Sorry, an internal server error occured. We'll get right on that :^)");
    header("Access-Control-Allow-Origin: *"); 
    header("Content-Type: application/json; charset=UTF-8"); 
    header("Access-Control-Allow-Methods: GET, POST");
    echo json_encode($usr_msg);
    logError($msg); //need to make the logError function do something
  }
  set_exception_handler('exceptionHandler');

  function errorHandler($errno, $errstr, $errfile, $errline) {
    if ($errno != 2 && $errno != 8) { //$errno is automatically generated by php when an error occurs, errno 2 & 8 are non fatal errors. 
      throw new Exception("Fatal Error Detected: [$errno] $errstr line: $errline", 1);
    } else {
      logError("Fatal Error Detected: [$errno] $errstr line: $errline \n");
    }
   }
   set_error_handler('errorHandler');

   function logError($msg) {
     if (is_array($msg)){
       error_log("Error occured on: ".date("d/m/Y")." at: ".date("h:i:sa")."\t Error Code: ".$msg['status']."\t Details: ".$msg['message']."\n", 3, "my-errors.log");
     } else {
       error_log($msg, 3, "my-errors.log");
     }
    }


  function autoloadClasses($className) {
  $filename = "classes\\" . strtolower($className) . ".class.php";
  $filename = str_replace('\\', DIRECTORY_SEPARATOR, $filename);
  if (is_readable($filename)) {
    include_once $filename;
  } else {
    throw new exception("File not found: " . $className . " (" . $filename . ")");
  }

  }
  spl_autoload_register("autoloadClasses");

  $ini['main'] = parse_ini_file("config.ini",true);


  define('BASEPATH', $ini['main']['paths']['basepath']);
  define('CSSPATH', $ini['main']['paths']['css']);
  define('JWTKEY', $ini['main']['jwtkey']['jwt']);

?>